### PR TITLE
Fix delete event redirect to events

### LINKED ISSUE #1452: On delete event there's no redirect
**Describe the bug**
After Delete the event, the toast is shown but remains in the deleted event page.

**To Reproduce**
1. Go to an event you have permission to delete
2. Click on "Cancelar evento"
3. see the toast but no redirection 

**Expected behavior**
Should redirect to events page.

### LINKED ISSUE #1453: all Select inputs are not respecting the dialog limit
**Describe the bug**
All select inputs are not with the rigth width.
"Criar instituição e Evento"

**To Reproduce**
1. Go to Create event
2. Try to select a country 

**Expected behavior**
image

**Screenshots**
image

### PR DESCRIPTION
**Pull request by MaianaB**
**Feature/Bug description:** When cancel the event show toast but not redirect to event pages and class of all md-select was overwritten.
Fixes #1452 
Fixes #1453 
**Solution:** Added state go and fix class of css.

**TODO/FIXME:** n/a

captura de tela de 2019-02-19 16-39-16
captura de tela de 2019-02-19 16-37-36
captura de tela de 2019-02-19 16-37-18

### CODE REVIEW

**Review by JuliePessoa — APPROVED** [review]

File: frontend/event/eventDetailsDirective.js [hunk 1]
```diff
@@ -42,6 +42,7 @@
             promise.then(function success() {
                 MessageService.showToast('Evento removido com sucesso!');
                 eventCtrl.event.state = "deleted";
+                $state.go(STATES.EVENTS);
```
Comment (raonismaneoto) [inline frontend/event/eventDetailsDirective.js:45]: checks that it is been called in the test

**Review by raonismaneoto — CHANGES_REQUESTED** [review]

**Review by ruanres — APPROVED** [review]

**Review by raonismaneoto — APPROVED** [review]
