### PR TITLE
Fix advanced institution search

### LINKED ISSUE #1469: Advanced Search of institution on mobile is not showing results.
**Bug Description**
"Area de atuação", "Natureza legal" and "localização" options are not showing results.
The backend request is done and returns the results, but nothing appears to the user.

**To Reproduce**
1. Go to "Search"
2. Click on 'Area de atuação"
3. Choose any options
4. Request is done but nothing is shown

### PR DESCRIPTION
**Pull request by raonismaneoto**
**Feature/Bug description:**
Fixes #1469

The search wasn't working for filters like actuation_area.

**Solution:**
Add an extra flow in the search function

**TODO/FIXME:** n/a

### CODE REVIEW

File: frontend/search/searchController.js [hunk 1]
```diff
@@ -25,10 +26,19 @@
             promise.then(function success(response) {
                 searchCtrl.institutions = response;
                 searchCtrl.loading = true;
+                searchCtrl.hasChanges = true;
             });
             return promise;
         };
 
+        searchCtrl.setHasChanges = () => {
+            if(searchCtrl.search_keyword)
```
Comment (JuliePessoa) [inline frontend/search/searchController.js]: do you agree that this is the same of: `searchCtrl.hasChanges = !!searchCtrl.search_keyword` or `searchCtrl.hasChanges = Boolean(searchCtrl.search_keyword)` ?

**Review by JuliePessoa — CHANGES_REQUESTED** [review]

**Review by brobsc — APPROVED** [review]

**Review by JuliePessoa — APPROVED** [review]
